[package]
name = "cpu_interrupts"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
x86_64 = { version = "0.14.10", features = ["inline_asm", "external_asm"] }
