[package]
name = "frame_buffer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader_api = "0.11.5"
noto-sans-mono-bitmap = "0.2.0"
