[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "machine_targets/theo.json"
# rustc flag to emit the generated llvm ir. you can inspect the eventual
# values of some of the configurations in the target triple json. for
# example, nounwind and noredzone can be easily spotted.
rustflags = ["--emit=llvm-ir"]
incremental = true
