[package]
name = "keyboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pc-keyboard = "0.7.0"
x86_64 = { version = "0.14.10", features = ["inline_asm", "external_asm"] }
